galaxy_info:
  author: Christoph Kern
  description: ACME dumper script to get certs out of Traefik

  license: GPLv3

  min_ansible_version: 2.4

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
