---
# tasks file for mailserver


- name: "Install mailserver packages"
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - postfix
    - dovecot
    - dovecot-mysql
    - dovecot-pigeonhole
    - fail2ban

- name: Start services for postfix, dovecot, and fail2ban
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - postfix.service
    - dovecot.service
    - fail2ban.service
  become: true

- name: Install postfix main.cf
  copy:
    src: postfix/main.cf
    dest: /etc/postfix/main.cf
    seuser: system_u
    setype: postfix_etc_t
  notify: restart postfix
  become: true

- name: Install postfix master.cf
  copy:
    src: postfix/master.cf
    dest: /etc/postfix/master.cf
    seuser: system_u
    setype: postfix_etc_t
  notify: restart postfix
  become: true

- name: Install dovecot db configs
  template:
    src: "postfix/{{ item }}"
    dest: "/etc/postfix/{{ item }}"
    seuser: system_u
    setype: postfix_etc_t
  notify: restart dovecot
  with_items:
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
  become: true



- name: Install dovecot configs
  copy:
    src: "{{ item }}"
    dest: /etc/dovecot/conf.d/
    seuser: system_u
    setype: dovecot_etc_t
  notify: restart dovecot
  become: true
  with_fileglob:
    - "{{ role_path }}/files/dovecot/*"

- name: Install dovecot db configs
  template:
    src: dovecot/dovecot-sql.conf.ext
    dest: /etc/dovecot/dovecot-sql.conf.ext
    seuser: system_u
    setype: dovecot_etc_t
  notify: restart dovecot
  become: true

# vmail

- name: Update default SELinux contexts for vmail
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "mail_spool_t"
    state: present
  with_items:
    - "/var/vmail"
  become: true

- name: Create /var/vmail
  file:
    path: /var/vmail
    state: directory
    owner: vmail
    group: vmail
  become: true

# groupadd -g 5000 vmail
- name: Create group vmail
  group:
    name: vmail
    state: present
    gid: 5000
    system: yes
  become: true

# useradd -g vmail -u 5000 vmail -d /var/vmail -Z system_u
- name: Create user vmail
  user:
    name: vmail
    state: present
    uid: 5000
    group: vmail
    system: yes
    create_home: no
    home: /var/vmail
    seuser: system_u
    shell: /bin/bash
  become: true


# rspamd configs
- name: Setup rspamd repo
  yum_repository:
    name: rspamd
    description: Rspamd stable repository
    baseurl: http://rspamd.com/rpm-stable/centos-7/x86_64/
    gpgkey: http://rspamd.com/rpm/gpg.key
    gpgcheck: true
  become: true

- name: Import rspamd key
  rpm_key:
    state: present
    key: https://rspamd.com/rpm-stable/gpg.key
  become: true

- name: Install rspamd
  yum:
    name: rspamd
    state: present
  become: true

- name: Copy rspamd override configs
  copy:
    src: "{{ item }}"
    dest: /etc/rspamd/override.d/
    owner: _rspamd
    group: _rspamd
  notify: restart rspamd
  become: true
  with_fileglob:
    - "{{ role_path }}/files/rspamd/override.d/*"

- name: Copy rspamd local configs
  copy:
    src: "{{ item }}"
    dest: /etc/rspamd/local.d/
    owner: _rspamd
    group: _rspamd
  notify: restart rspamd
  become: true
  with_fileglob:
    - "{{ role_path }}/files/rspamd/local.d/*"

- name: Start rspamd
  systemd:
    name: "rspamd.service"
    state: started
    enabled: yes
    daemon_reload: yes
  become: true

- name: Create DKIM directory
  file:
    path: /var/lib/rspamd/dkim
    owner: _rspamd
    group: _rspamd
  become: true


# SELinxu configs
- name: Update default SELinux contexts for containers
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "container_file_t"
    state: present
  with_items:
    - "/var/srv/mailserver/data"
    - "/var/srv/mailserver/db.conf.d"
    - "/var/srv/mailserver/sogo"
    - "/var/srv/mailserver/nginx"
  become: true

- name: Update default SELinux contexts for postfix TLS
  sefcontext:
    target: "{{ item }}(/.*)?"
    setype: "postfix_etc_t"
    state: present
  with_items:
    - "/var/srv/mailserver/ssl"
  become: true

- name: Deploy sogo.conf
  template:
    src: sogo/sogo.conf
    dest: "/var/srv/mailserver/sogo/sogo.conf"
    setype: "container_file_t"
  become: true

- name: Deploy nginx.conf
  template:
    src: nginx/nginx.conf
    dest: "/var/srv/mailserver/nginx/nginx.conf"
    setype: "container_file_t"
  become: true

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "/var/srv/mailserver/docker-compose.yml"
  become: true

- name: Compose mailserver docker
  docker_service:
    state: present
    project_src:  "/var/srv/mailserver/"
    pull: yes
  become: true

- name: Install export.sh
  copy:
    src: export/script.sh
    dest: /var/srv/mailserver/export.sh
    mode: 0755
  become: true

- name: Install systemd service
  copy:
    src: export/systemd.{{ item }}
    dest: /etc/systemd/system/export.{{ item }}
    seuser: system_u
    setype: systemd_unit_file_t
    serole: object_r
    mode: 0644
  with_items:
    - service
    - timer
  become: true

- name: run export.sh
  command: /var/srv/mailserver/export.sh
  args:
    creates: /var/srv/mailserver/ssl/fullchain.pem
  become: true

- name: Enable export.timer
  systemd:
    name: export.timer
    state: started
    enabled: true
  become: true


# Firewall configs
- name: firewall configs
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - smtp
    - pop3s
    - imaps
  become: true

- name: firewall configs
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  with_items:
    - 587
    - 465
    - 4190
  become: true

- name: firewall configs
  firewalld:
    port: "{{ item }}/tcp"
    state: disabled
    permanent: true
    immediate: true
  with_items:
    - 110
    - 143
  become: true
