---

- name: Install SSMTP
  apt:
    name: ssmtp
    state: present
  become: true

- name: Install ssmtp.conf
  template:
    src: ssmtp.conf
    dest: "/etc/ssmtp/ssmtp.conf"
    mode: 0600
  become: true
