galaxy_info:
  author: Christoph Kern
  description: Installs ssmtp on a host
  license: GPLv3

  min_ansible_version: 2.4
  platforms:
    - name: CentOS
      versions:
        - 7
    - name: Debian
      version:
        - 8
  galaxy_tags: []

dependencies:
  - docker
  - docker-compose
