---
# tasks file for nextcloud

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
#   setype: "container_file_t"
  with_items:
    - "{{ nextcloud_install_location }}"
    - "{{ nextcloud_apps_location }}"
    - "{{ nextcloud_config_location }}"
    - "{{ nextcloud_data_location }}"
    - "{{ nextcloud_database_location }}"

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ nextcloud_install_location }}/docker-compose.yml"
  register: docker_compose_yml
  tags:
    - docker
    - nextcloud

- name: Compose nextcloud
  docker_service:
    project_src:  "{{ nextcloud_install_location }}"
# command: "docker-compose up -d"
# args:
#   chdir: "{{ nextcloud_install_location }}"
# when: docker_compose_yml|changed

- stat: path="{{ nextcloud_config_location }}/config.php"
  register: nextcloud_config_php

- command: docker-compose ps -q nextcloud
  register: nextcloud_container
  args:
    chdir: "{{ nextcloud_install_location }}"
  when: nextcloud_config_php.stat.exists == False

- name: Sleep to let everything come up
  pause:
    minutes: 1

- name: Configure nextcloud
  command: docker exec -u 33 nextcloud_nextcloud_1 /usr/local/bin/php ./occ maintenance:install --database=mysql --database-host=database --database-name=nextcloud --database-user=nextcloud --database-pass={{ nextcloud_db_password }} --admin-user={{ nextcloud_admin_user }} --admin-pass={{ nextcloud_admin_password }}
  args:
    chdir: "{{ nextcloud_install_location }}"
  when: nextcloud_config_php.stat.exists == False
