---
- name: Install docker-compose dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "docker-compose"


# name: Install docker-compose
# get_url:
#   url: "{{ dockercompose_url }}"
#   dest: "{{ dockercompose_install_dir }}"
#   mode: a+x
