---

- name: restart dovecot
  systemd:
    name: dovecot.service
    state: restarted
    daemon_reload: yes
  become: true

- name: restart postfix
  systemd:
    name: postfix.service
    state: restarted
    daemon_reload: yes
  become: true

- name: restart rspamd
  systemd:
    name: rspamd.service
    state: restarted
    daemon_reload: yes
  become: true

- name: restart fail2ban
  systemd:
    name: fail2ban.service
    state: restarted
    daemon_reload: yes
  become: true
