{{ ansible_managed | comment }}
version: '2'
services:
  proxy:
    image: traefik:{{ traefik_version }}
    ports:
    - "80:80"
    - "443:443"
{% if traefik_debug is defined %}
    - "8080:8080"
{% endif %}

    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "{{ traefik_acme_location }}:/etc/traefik/acme"
    command: "-c /dev/null --web --docker --acme --acme.email={{ traefik_LE_email }} --acme.storage=/etc/traefik/acme/acme.json --acme.entryPoint=https --acme.onhostrule --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --defaultentrypoints=http,https --docker.exposedbydefault=false --logLevel=DEBUG"
    networks:
      {{ proxy_network }}:

networks:
   {{ proxy_network }}:
     external: true
